name=uno_tb6612_hc04
version=1.0.0
author=ddDog
maintainer=ddDog
sentence=Platform and per-ALG params for uno_tb6612_hc04 sketches
paragraph=Platform parameters for Arduino Uno + TB6612 + HC-SR04 sketches in this repo.
category=Device Control
url=
architectures=avr
includes=uno_tb6612_hc04.h
