#pragma once
// 电机正反转修正。某侧反了可在 sketch 里 #include 之前定义：
//   #define UNO_TB6612_MOTOR_LEFT_REVERSE  1
//   #define UNO_TB6612_MOTOR_RIGHT_REVERSE 1

#ifndef UNO_TB6612_MOTOR_LEFT_REVERSE
#define UNO_TB6612_MOTOR_LEFT_REVERSE 0
#endif
#ifndef UNO_TB6612_MOTOR_RIGHT_REVERSE
#define UNO_TB6612_MOTOR_RIGHT_REVERSE 0
#endif

const bool MOTOR_LEFT_DIR_REVERSE  = (UNO_TB6612_MOTOR_LEFT_REVERSE != 0);
const bool MOTOR_RIGHT_DIR_REVERSE = (UNO_TB6612_MOTOR_RIGHT_REVERSE != 0);
